---
title: "Reproducible workflows with the [drake](https://github.com/ropensci/drake) R package"
subtitle: "make for R"
author: "Kirill Müller"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    output_dir: "docs"
    lib_dir: docs/libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(width = 65)
knit_print.data.frame <- function(x, ...) paste0(format(as_tibble(x)), collapse = "\n")
knitr::opts_chunk$set(collapse = TRUE)
knitr::opts_chunk$set(fig.path = "index_files/figure-html/")

pkgconfig::set_config_in("drake::strings_in_dots" = "literals", .in = globalenv())
```

# Why *drake*?

1. too many slow R scripts?

1. *rmarkdown* code chunks too heavy?


&nbsp;

.right[

# Save time and ensure reproducibility!

## data analysis → set of data transformations

]

---

```{r cleanup, include = FALSE}
unlink(".drake", recursive = TRUE)
```

```{r plan-base-vis, include = FALSE}
library(drake)
library(tidyverse)
create_plot <- function(data) {
  ggplot(data, aes(x = Petal.Width, fill = Species)) +
    geom_histogram()
}

plan <- drake_plan(
  raw_data = readxl::read_xlsx(file_in("raw-data.xlsx")),

  data = mutate(raw_data, Species = forcats::fct_inorder(Species)),
  
  hist = create_plot(data),
  
  fit = lm(Sepal.Width ~ Petal.Width + Species, data),
  
  report = rmarkdown::render(
    knitr_in("report.Rmd"),
    output_file = file_out("report.pdf"),
    quiet = TRUE
  )
)
```

```{r vis-intro, echo = FALSE}
config <- drake_config(plan, verbose = FALSE)
# Adding report.Rmd to the set of from nodes didn't work with xaringan/remark.js
# No end of slide marker was detected
vis_drake_graph(
  config,
  from = file_store("raw-data.xlsx"), mode = "out",
  build_times = "none", ncol_legend = 0,
  width = "100%",
  hover = FALSE
)
```

---

```{r plan-base}
library(drake)
library(tidyverse)

create_plot <- function(data) {
  ggplot(data, aes(x = Petal.Width, fill = Species)) +
    geom_histogram()
}

plan <- drake_plan(
  raw_data = readxl::read_xlsx(file_in("raw-data.xlsx")),
  
  data = raw_data %>%
    mutate(Species = forcats::fct_inorder(Species)),
  
  hist = create_plot(data),
  
  fit = lm(Sepal.Width ~ Petal.Width + Species, data),
  
  report = rmarkdown::render(
    knitr_in("report.Rmd"),
    output_file = file_out("report.pdf"),
    quiet = TRUE
  )
)
```

---

```{r plan-base-show}
plan
```

---

.pull-left[

```{r make}
make(plan)
```

]

.pull-right[

```{r make-report, echo = FALSE}
magick::image_read("report.pdf", density = 300) %>%
  magick::image_resize(magick::geometry_size_percent(50)) %>%
  magick::image_border() %>%
  magick::image_draw(res = 300)
```

]

---

```{r fit}
summary(readd(fit))
```

---

```{r data}
loadd(data, hist)
data
```

---

```{r better-plan}
create_plot <- function(data) {
  ggplot(data, aes(x = Petal.Width, fill = Species)) +
    geom_histogram()
}

plan <- drake_plan(
  raw_data = readxl::read_xlsx(file_in("raw-data.xlsx")),

  data = raw_data %>% 
    mutate(Species = forcats::fct_inorder(Species)) %>%
    select(Sepal.Length:Species), #<<
  
  hist = create_plot(data),
  
  fit = lm(Sepal.Width ~ Petal.Width + Species, data),
  
  report = rmarkdown::render(
    knitr_in("report.Rmd"),
    output_file = file_out("report.pdf"),
    quiet = TRUE
  )
)
```

---

```{r vis-stale, echo = FALSE}
config <- drake_config(plan, verbose = FALSE)
vis_drake_graph(
  config,
  from = file_store("raw-data.xlsx"), mode = "out",
  build_times = "none", full_legend = FALSE,
  width = "100%",
  hover = FALSE
)
```

---

```{r make-fixed}
make(plan)
readd(data)
```

---

```{r show-hist}
readd(hist)
```

---

```{r best-plan}
create_plot <- function(data) {
  ggplot(data, aes(x = Petal.Width, fill = Species)) +
    geom_histogram(binwidth = 0.25) + #<<
    theme_gray(20) #<<
}

plan <- drake_plan(
  raw_data = readxl::read_xlsx(file_in("raw-data.xlsx")),

  data = raw_data %>% 
    mutate(Species = forcats::fct_inorder(Species)) %>%
    select(Sepal.Length:Species),
  
  hist = create_plot(data),
  
  fit = lm(Sepal.Width ~ Petal.Width + Species, data),
  
  report = rmarkdown::render(
    knitr_in("report.Rmd"),
    output_file = file_out("report.pdf"),
    quiet = TRUE
  )
)
```

---

```{r cleanup-env, include = FALSE}
rm(fit, hist, data)
```

.pull-left[

```{r make-fixed-hist}
make(plan)
```

]

.pull-right[

```{r make-report-fixed-hist, echo = FALSE}
magick::image_read("report.pdf", density = 300) %>%
  magick::image_resize(magick::geometry_size_percent(50)) %>%
  magick::image_border() %>%
  magick::image_draw(res = 300)
```

]

---

```{r vis-full, echo = FALSE}
config <- drake_config(plan, verbose = FALSE)
vis_drake_graph(
  config,
  build_times = "none", full_legend = FALSE,
  width = "100%",
  hover = FALSE
)
```

---

class: inverse, middle, center
